server:
  port: 8080

security:
    oauth2:
        client:
            access-token-uri: https://dev-872814.oktapreview.com/oauth2/default/v1/token
            user-authorization-uri: https://dev-872814.oktapreview.com/oauth2/default/v1/authorize
            client-id: 0oahconykz3JdCVDD0h7
            scope: openid profile email
        resource:
            user-info-uri: https://dev-872814.oktapreview.com/oauth2/default/v1/userinfo
            token-info-uri: https://dev-872814.oktapreview.com/oauth2/default/v1/introspect
            prefer-token-info: false

spring:
  datasource:
    #SPRING_DATASOURCE_URL environment variable will be something like -> jdbc:sqlserver://MySqlServer\\MyInstance:1433;DatabaseName=MyDbName;
    url: jdbc:mysql://localhost:3306/GreenCrunch?autoReconnect=true&useSSL=false
    username: root
    password: CJ_Database
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true